controllerModule.config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('en', {
            // ACCOUNT
            "TITLE_LOGIN": 'Login to Robotics',
            "USERNAME": 'Username',
            "PASSWORD": 'Password',
            "LOGIN": 'Login',
            "LOGOUT": 'Logout',
            // CRUD
            "CREATE": 'Create',
            "UPDATE": 'Update',
            "DELETE": 'Delete',
            "EDIT": 'Edit',
            "CANCEL": 'Cancel',
            // COMMON
            "NAME": 'Name',
            "NUMBER": 'Number',
            "ADDRESS": 'Address',
            "STREETNUMBER": 'Streetnumber',
            "CITY": 'City',
            "ZIPCODE": 'Zipcode',
            "EMAIL": 'Email',
            "TIMESTART": 'Starting time',
            "TIMEEND": 'Ending time',
            "START": 'Start',
            "END": 'End',
            "CLIENT": 'Client',
            // PAGE SPECIFIC
            "HOME_WELCOME_MESSAGE": 'Welcome to GuardSwift',
            "GUARDS": 'Guards',
            "GUARDS_CREATE": 'Create guard',
            "GUARDS_LIST": 'Guards in database',
            "GUARD_ID": 'Guard id',
            "CLIENTS": 'Clients',
            "CLIENTS_CREATE": 'Create client',
            "CLIENTS_LIST": 'Clients in database',
            "CLIENTS_SELECT": 'Select client',
            "CIRCUITS": 'Circuits',
            "CIRCUITS_CREATE": 'Create circuit',
            "CIRCUITS_LIST": 'Circuits in database',
            "CIRCUITS_SELECT": 'Select circuit',
            "CIRCUITUNITS": 'CircuitUnits',
            "CIRCUITUNITS_NONE_SELECTED": 'No circuit selected',
            "CIRCUITUNITS_CREATE": 'Create circuitunit under: ',
            "CIRCUITUNITS_LIST": 'Circuitunits in database',
        });
        $translateProvider.translations('ru', {
            // ACCOUNT
            "TITLE_LOGIN": 'Log på GuardSwift',
            "USERNAME": 'Brugernavn',
            "PASSWORD": 'Kodeord',
            "LOGIN": 'Log ind',
            "LOGOUT": 'Log ud',
            // CRUD
            "CREATE": 'Opret',
            "UPDATE": 'Gem',
            "DELETE": 'Slet',
            "EDIT": 'Rediger',
            "CANCEL": 'Annuller',
            // COMMON
            "NAME": 'Navn',
            "NUMBER": 'Nummer',
            "ADDRESS": 'Adresse',
            "STREETNUMBER": 'Husnummer',
            "CITY": 'By',
            "ZIPCODE": 'Postnummer',
            "EMAIL": 'Email',
            "TIMESTART": 'Start tidspunkt',
            "TIMEEND": 'Slut tidspunkt',
            "START": 'Start',
            "END": 'Slut',
            "CLIENT": 'Kunde',
            // PAGE SPECIFIC
            "HOME_WELCOME_MESSAGE": 'Velkommen til GuardSwift',
            "GUARDS": 'Vagter',
            "GUARDS_CREATE": 'Opret vagt',
            "GUARDS_LIST": 'Vagter',
            "GUARD_ID": 'Vagt id',
            "CLIENTS": 'Kunder',
            "CLIENTS_CREATE": 'Opret kunde',
            "CLIENTS_LIST": 'Kunder',
            "CLIENTS_SELECT": 'Vælg kunde',
            "CIRCUITS": 'Kreds',
            "CIRCUITS_CREATE": 'Opret kreds',
            "CIRCUITS_LIST": 'Kreds oversigt',
            "CIRCUITS_SELECT": 'Vælg kreds',
            "CIRCUITUNITS": 'Tilsyn',
            "CIRCUITUNITS_NONE_SELECTED": 'Der er ikke valgt nogen kreds',
            "CIRCUITUNITS_CREATE": 'Opret tilsyn under kreds: ',
            "CIRCUITUNITS_LIST": 'Tilsyn',
        });
        $translateProvider.preferredLanguage('en');
    }]);

